(function(root){
 'use strict';
 const copy=value=>JSON.parse(JSON.stringify(value));
 function validDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(value+'T00:00:00Z');return Number.isFinite(date.getTime())&&date.toISOString().slice(0,10)===value;}
 function addDays(day,n){if(!validDate(day))throw Error('日付が正しくありません');const date=new Date(day+'T00:00:00Z');date.setUTCDate(date.getUTCDate()+n);return date.toISOString().slice(0,10);}
 function fresh(){return {version:1,revision:0,days:[],cycles:{},sessions:{},events:[]};}
 function validate(s){if(!s||s.version!==1||!Number.isInteger(s.revision)||s.revision<0||!Array.isArray(s.days)||!s.days.every(validDate)||!Array.isArray(s.events)||!s.cycles||Array.isArray(s.cycles)||!s.sessions||Array.isArray(s.sessions))throw Error('保存データの形式を確認できません');for(const c of Object.values(s.cycles)){if(!c||!validDate(c.started)||!Array.isArray(c.questions)||!c.questions.every(x=>typeof x==='string')||!Array.isArray(c.reviews)||c.reviews.length!==2||!c.reviews.every(r=>[3,14].includes(r.interval)&&validDate(r.due)&&(!r.completed||validDate(r.completed))))throw Error('復習データの形式を確認できません');}for(const se of Object.values(s.sessions)){if(!se||!Array.isArray(se.queue)||!se.queue.every(q=>typeof q==='string')||!Array.isArray(se.scope)||!Number.isInteger(se.index)||se.index<0||se.index>se.queue.length||!['today','free','review'].includes(se.mode))throw Error('学習データの形式を確認できません');}return s;}
 function due(s,day){return Object.values(s.cycles).flatMap(c=>c.reviews.filter(r=>!r.completed&&r.due<=day).map(r=>({...r,unitId:c.unitId,name:c.name}))).sort((a,b)=>a.due.localeCompare(b.due)||a.interval-b.interval);}
 function start(s,unit,mode,reviewId,id){const n=copy(s);if(!['today','free','review'].includes(mode))throw Error('学習モードが正しくありません');const existing=Object.values(n.sessions).find(x=>!x.completed&&x.unitId===unit.id&&x.mode===mode&&x.reviewId===reviewId);if(existing)return {state:n,id:existing.id};let scope=unit.questions.map(q=>q.id);if(mode==='review'){const c=n.cycles[unit.id];const r=c?.reviews.find(x=>x.id===reviewId&&!x.completed);if(!r)throw Error('復習が見つかりません');scope=c.questions.slice();}if(!scope.length)throw Error('問題がありません');n.sessions[id]={id,unitId:unit.id,name:unit.name,mode,reviewId,scope,queue:scope.slice(),index:0,completed:null};return {state:n,id};}
 function answer(s,sessionId,index,result,day){if(!validDate(day))throw Error('日付が正しくありません');if(!['known','again'].includes(result))throw Error('解答の判定が正しくありません');const n=copy(s),se=n.sessions[sessionId];if(!se)throw Error('学習が見つかりません');if(se.completed||se.index!==index)return n;const q=se.queue[se.index],eventId=`${sessionId}:${index}`;if(n.events.some(e=>e.id===eventId))return n;
 if(se.mode==='today'&&!n.cycles[se.unitId])n.cycles[se.unitId]={unitId:se.unitId,name:se.name,started:day,questions:se.scope.slice(),reviews:[3,14].map(interval=>({id:`${se.unitId}:${interval}`,interval,due:addDays(day,interval),completed:null}))};
 n.events.push({id:eventId,sessionId,questionId:q,result,day,mode:se.mode});if(!n.days.includes(day))n.days.push(day);if(se.mode!=='review'&&result==='again')se.queue.push(q);se.index++;
 if(se.index===se.queue.length){se.completed=day;if(se.mode==='review'){const r=n.cycles[se.unitId].reviews.find(r=>r.id===se.reviewId);if(!r.completed)r.completed=day;}}return n;}
 const api={copy,validDate,addDays,fresh,validate,due,start,answer};if(typeof module!=='undefined')module.exports=api;else root.LearningCore=api;
})(typeof window==='undefined'?globalThis:window);
