const Study=(()=>{
 const C=LearningCore,KEY='socialQuestPilotV1';let state=C.fresh(),raw=null,blocked=false,sessionId=null,shownIndex=null,answerVisible=false,dateOverride='';
 function today(){if(dateOverride)return dateOverride;const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
 function fail(error){blocked=true;const b=document.getElementById('save-warning');b.hidden=false;b.textContent=`記録の保存を停止しました。${error.message}。元の記録は残しています。ページを再読み込みして確認してください。`;}
 function commit(next){if(blocked)return false;try{if(localStorage.getItem(KEY)!==raw)throw Error('別の画面で記録が更新されています');next.revision=state.revision+1;const encoded=JSON.stringify(next);localStorage.setItem(KEY,encoded);raw=encoded;state=next;return true;}catch(e){fail(e);return false;}}
 function init(){const warning=document.createElement('p');warning.id='save-warning';warning.hidden=true;warning.className='save-warning';warning.setAttribute('role','alert');document.querySelector('header').after(warning);try{raw=localStorage.getItem(KEY);if(raw!==null)state=C.validate(JSON.parse(raw));}catch(e){fail(e);}window.addEventListener('storage',e=>{if(e.key===KEY||e.key===null)fail(Error('別の画面で記録が変更されました'));});
 const main=document.createElement('main');main.id='study';main.hidden=true;document.getElementById('collection').after(main);
 const dateBox=document.createElement('label');dateBox.append('確認用の日付 ');const input=document.createElement('input');input.type='date';input.id='pilot-date';input.value=today();dateBox.append(input);const button=document.createElement('button');button.textContent='この日付で確認';button.addEventListener('click',()=>{if(!C.validDate(input.value)){input.reportValidity();return;}if(location.hash==='#study'){notice('トップで日付を変更してください','学習中の日付は切り替えません。途中の記録を残してトップに戻ると変更できます。');return;}dateOverride=input.value;document.querySelector('.preview>div>span').textContent='開発版の記録を使用中・確認日：'+dateOverride;preview.review='live';renderHome();if(location.hash==='#collection')renderCollection();});document.querySelector('.controls').append(dateBox,button);
 const live=document.createElement('button');live.textContent='学習記録の表示に戻す';live.addEventListener('click',()=>{preview.review='live';renderHome();if(location.hash==='#collection')renderCollection();});document.querySelector('.controls').append(live);
 }
 function growth(){return {level:Math.min(100,1+Math.floor(state.days.length/3)),days:3-state.days.length%3};}
 function renderHome(){const list=document.getElementById('review-list');list.replaceChildren();const tasks=C.due(state,today());const completed=Object.values(state.cycles).flatMap(c=>c.reviews).some(r=>r.completed===today());document.getElementById('review-count').hidden=!tasks.length;document.getElementById('review-count').textContent=tasks.length;document.getElementById('speech').textContent=completed?(tasks.length?`復習、頑張ったね！ あと${tasks.length}つ、一緒に取り組もう。`:'今日の復習、よく頑張ったね！ 一歩ずつ力になっているよ。'):tasks.length?`今日は復習が${tasks.length}つあるよ。思い出すところから始めよう！`:'今日も会えてうれしいな！ 気になる学びに出かけよう。';
 for(const task of tasks){const b=el('button','review-card');b.append(el('span','review-badge',`${task.interval}日後の復習`));const text=el('span');text.append(el('strong','',`地理｜${task.name}`),el('small','',`${task.due} の予定${task.due<today()?'・未完了の復習です':''}`));b.append(text,el('span','review-arrow','復習する →'));b.addEventListener('click',()=>launch('review',task.id));list.append(b);}if(!tasks.length)list.append(el('div','empty-review',completed?'✓ 今日の復習が終わりました。頑張ったね！':'今日の復習はありません。新しい学びを楽しもう！'));
 const pending=Object.values(state.sessions).filter(s=>!s.completed);if(pending.length){const b=el('button','resume','途中の学習を続ける →');b.addEventListener('click',()=>{sessionId=pending[pending.length-1].id;preview.review='live';location.hash='study';render();});list.append(b);}
 }
 function select(){if(blocked){notice('記録を確認してください','画面上部に保存についての案内があります。再読み込みして確認してください。');return;}const dialog=document.getElementById('notice');document.getElementById('notice-title').textContent='地理｜単元を選ぶ';const body=document.getElementById('notice-body');body.replaceChildren(el('strong','',PILOT_UNIT.name),el('p','',`世界の姿・${PILOT_UNIT.questions.length}問。今回はこの単元で学習できます。`));for(const [mode,label] of [['today','今日の授業として始める'],['free','自由に学習する']]){const b=el('button','primary',label);b.addEventListener('click',()=>{dialog.close();launch(mode,null);});body.append(b);}dialog.showModal();}
 function launch(mode,reviewId){if(blocked)return;const started=C.start(state,PILOT_UNIT,mode,reviewId,crypto.randomUUID());if(!commit(started.state))return;sessionId=started.id;preview.review='live';location.hash='study';render();}
 function showImage(file,label){const img=el('img','question-image');img.src=`images/geography/${file}`;img.alt=label;const b=el('button','image-button');b.setAttribute('aria-label',label+'を拡大');b.append(img);b.addEventListener('click',()=>{const d=document.getElementById('image-viewer');d.querySelector('img').src=img.src;d.querySelector('img').alt=label;d.showModal();});return b;}
 function render(){const main=document.getElementById('study');main.replaceChildren();const se=state.sessions[sessionId];if(!se){location.hash='home';return;}const back=el('button','back','← 記録を残してトップへ');back.addEventListener('click',()=>{location.hash='home';});main.append(back,el('p','eyebrow',se.mode==='review'?'復習クエスト':se.mode==='today'?'今日の授業':'自由学習'),el('h1','',se.name));if(se.completed){main.append(el('div','empty-review','✓ この学習が終わりました。お疲れさま！'));const cycle=state.cycles[se.unitId];if(cycle)main.append(el('p','',`復習予定：${cycle.reviews.map(r=>`${r.due}${r.completed?'（完了）':''}`).join(' ／ ')}`));return;}
 shownIndex=se.index;answerVisible=false;const q=PILOT_UNIT.questions.find(q=>q.id===se.queue[se.index]);if(!q){fail(Error('問題を読み込めません'));return;}main.append(el('p','',`残り${se.queue.length-se.index}問 ／ ${q.category}`));const panel=el('section','question-panel');panel.append(el('h2','',q.text||'画像の問題を考えよう'));if(q.image)panel.append(showImage(q.image,'問題画像'));const answer=el('div','answer-panel');answer.hidden=true;answer.append(el('strong','','答え'),el('p','',q.answer));if(q.explanation){const detail=el('details');detail.append(el('summary','','解説を見る'),showImage(q.explanation,'解説画像'));answer.append(detail);}const reveal=el('button','primary','答えを見る');const actions=el('div','answer-actions');actions.hidden=true;for(const [value,label] of [['known','できた'],['again','もう一度']]){const b=el('button',value==='known'?'primary':'back',label);b.addEventListener('click',()=>{if(!answerVisible||blocked)return;answerVisible=false;const next=C.answer(state,se.id,shownIndex,value,today());if(commit(next)){renderHome();render();}else{answerVisible=true;}});actions.append(b);}reveal.addEventListener('click',()=>{answerVisible=true;answer.hidden=false;actions.hidden=false;reveal.hidden=true;});panel.append(reveal,answer,actions);main.append(panel);if(se.mode==='review')main.append(el('p','study-note','答えを確認して「できた」か「もう一度」を選ぼう。全問を確認すると、この復習は完了です。'));else main.append(el('p','study-note','「もう一度」にした問題は、最後にもう一度出てくるよ。'));}
 return {init,today,growth,renderHome,select,render};
})();
