// 通常学習と共通の「知ってる！」「次の問題へ」で操作する。
let activeWeak=null,weakBusy=false,weakShownTurn=0;
const sampleWeak=new URLSearchParams(location.search).has('sampleWeak');
let answerEventId=crypto.randomUUID(),answerRecorded=false;
function weakError(e){let p=$('weak-error');if(!p){p=document.createElement('p');p.id='weak-error';p.setAttribute('role','alert');p.style.cssText='padding:16px;background:#fff0e6;color:#8c2929';document.body.prepend(p);}p.textContent='記録を保存・読み込みできません。元の記録は残しています。'+e.message;}
function resetAnswerRecord(){answerEventId=crypto.randomUUID();answerRecorded=false;}
async function recordNormalAnswer(result){if(answerRecorded)return true;try{if(!sampleReview)await QuestWeak.record(current,result,answerEventId);answerRecorded=true;return true;}catch(e){weakError(e);return false;}}
function openRequestedWeak(){const id=new URLSearchParams(location.search).get('weak');if(!id)return false;try{const se=QuestWeak.session(sampleWeak);if(!se||se.id!==id)throw Error('対象のセットがありません。トップから開いてください。');activeWeak=id;if(sampleWeak){const p=document.createElement('p');p.textContent='お試し苦手問題：学習記録や成長には保存されません。';p.style.cssText='padding:16px;background:#fff4cf';document.body.prepend(p);}showWeakQuestion();}catch(e){showReviewMessage('苦手な問題を開けません。トップへ戻って確認してください。');weakError(e);}return true;}
function updateWeakProgress(se){const n=Object.keys(se.known).length;$('progressText').textContent=`進捗 ${n}問 / ${se.queue.length}問　${Math.round(n/se.queue.length*100)}%`;$('bar').style.width=100*n/se.queue.length+'%';$('known').disabled=!!se.known[se.queue[se.index]];$('known').classList.toggle('known-done',$('known').disabled);$('known').textContent=$('known').disabled?'知ってる！登録済み':'知ってる！';$('next').disabled=!!se.completed;$('back').classList.toggle('back-complete',!!se.completed);weakShownTurn=se.turn;}
function showWeakQuestion(){const se=QuestWeak.session(sampleWeak),key=se.queue[se.index],subject=DATA[0]?.subject==='hist'?'hist':'geo';if(!key.startsWith(subject+':')){location.replace(QuestWeak.route(se,sampleWeak,'../'));return;}current=DATA.find(q=>QuestWeak.identity(q)===key);if(!current)throw Error('問題が見つかりません');$('selectScreen').classList.add('hidden');$('studyScreen').classList.remove('hidden');$('back').textContent='トップへ戻る';$('back').onclick=()=>location.href='../index.html#home';resetResponsePanels();$('answer').classList.add('text-answer');$('answer').innerHTML=`<div class="fit-text" id="answerTextFit">${esc(current.answer)}</div>`;$('next').textContent='次の問題へ';prepareExplanationButton();renderQuestionArea();updateWeakProgress(se);}
async function answerWeak(result){if(weakBusy)return;weakBusy=true;try{const se=await QuestWeak.answer(activeWeak,weakShownTurn,result,sampleWeak);if(!sampleWeak)QuestProgress.record();if(result==='known')updateWeakProgress(se);else showWeakQuestion();}catch(e){weakError(e);}finally{weakBusy=false;}}
const normalKnown=markKnown;
$('known').onclick=async()=>{if(activeWeak){await answerWeak('known');return;}if(weakBusy)return;weakBusy=true;try{if(current&&await recordNormalAnswer('known'))normalKnown();}finally{weakBusy=false;}};
$('next').onclick=async()=>{if(activeWeak){await answerWeak('next');return;}if(weakBusy)return;weakBusy=true;try{if(current&&!await recordNormalAnswer('again'))return;showNextQuestion(true);}finally{weakBusy=false;}};
